export const MOCK_USERS = {
  CITIZEN: {
    id: 'user-cit-001',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@example.com',
    phone: '+91 98930 12345',
    role: 'CITIZEN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    ward: 'Ward 48 - Arera Colony',
    points: 450,
    badge: 'Green Champion',
  },
  WORKER: {
    id: 'user-wrk-102',
    name: 'Vikram Singh',
    email: 'vikram.singh@bhopal.gov.in',
    phone: '+91 94250 67890',
    role: 'WORKER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    ward: 'Ward 43 - MP Nagar Zone I',
    department: 'Roads & Civil Infrastructure',
    points: 820,
    badge: 'Field Star',
  },
  NODAL_OFFICER: {
    id: 'user-nod-201',
    name: 'Er. Sunita Verma',
    email: 'sunita.verma@bhopal.gov.in',
    phone: '+91 75525 54321',
    role: 'NODAL_OFFICER',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    ward: 'Zone 8 (Wards 42-49)',
    department: 'Municipal Works Division',
  },
  NGO: {
    id: 'user-ngo-301',
    name: 'Green Bhopal Foundation',
    email: 'contact@greenbhopal.org',
    phone: '+91 75540 99887',
    role: 'NGO',
    avatar: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=150&auto=format&fit=crop&q=80',
    organization: 'Green Bhopal Foundation',
    ward: 'City-wide Urban Environment',
  },
  HIGHER_AUTHORITY: {
    id: 'user-aut-401',
    name: 'Dr. Ananya Mishra, IAS',
    email: 'commissioner@bhopal.gov.in',
    phone: '+91 75527 10001',
    role: 'HIGHER_AUTHORITY',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Bhopal Municipal Corporation Administration',
  },
  SUPER_ADMIN: {
    id: 'user-adm-501',
    name: 'Smart Bhopal SysAdmin',
    email: 'admin@smartbhopal.gov.in',
    phone: '+91 75527 99999',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_COMPLAINTS = [
  {
    id: 'SB-2026-8901',
    title: 'Severe Deep Potholes on Link Road 1 near Board Office Square',
    description: 'Multiple continuous potholes causing severe traffic slows and hazard to two-wheelers during heavy monsoon showers.',
    category: 'Roads & Potholes',
    status: 'In Progress',
    priority: 'HIGH',
    location: {
      address: 'Link Road 1, Near Board Office Square, MP Nagar Zone I',
      ward: 'Ward 43 - MP Nagar Zone I',
      lat: 23.2315,
      lng: 77.4338,
    },
    citizenId: 'user-cit-001',
    citizenName: 'Rajesh Sharma',
    citizenPhone: '+91 98930 12345',
    images: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80'],
    createdAt: '2026-08-21T09:30:00Z',
    updatedAt: '2026-08-22T14:15:00Z',
    estimatedResolutionDays: 2,
    assignedWorkerId: 'user-wrk-102',
    assignedWorkerName: 'Vikram Singh',
    assignedWorkerPhone: '+91 94250 67890',
    assignedDepartment: 'Road Maintenance & Asphalt Wing',
    nodalOfficerId: 'user-nod-201',
    nodalOfficerName: 'Er. Sunita Verma',
    aiAnalysis: {
      autoCategory: 'Roads & Potholes',
      predictedPriority: 'HIGH',
      confidenceScore: 0.94,
      isDuplicateDetected: false,
      recommendedWorkerDept: 'Road Maintenance & Asphalt Wing',
      imageVerified: true,
      imageVerificationNote: 'AI verified authentic pothole damage in MP Nagar Zone I area.',
    },
    timeline: [
      {
        id: 'tl-1',
        status: 'Submitted',
        title: 'Complaint Registered',
        description: 'Issue reported with geotagged photo evidence by Citizen.',
        timestamp: '2026-08-21T09:30:00Z',
        performedBy: 'Rajesh Sharma',
        role: 'CITIZEN',
      },
      {
        id: 'tl-2',
        status: 'In Review',
        title: 'AI Verification & Nodal Inspection',
        description: 'AI validated pothole image with 94% confidence. Assigned to Ward 43 officer.',
        timestamp: '2026-08-21T10:15:00Z',
        performedBy: 'Er. Sunita Verma',
        role: 'NODAL_OFFICER',
      },
      {
        id: 'tl-3',
        status: 'Assigned',
        title: 'Dispatched to Field Worker',
        description: 'Task assigned to Sr. Asphalt Tech Vikram Singh with target completion 48h.',
        timestamp: '2026-08-21T11:00:00Z',
        performedBy: 'Er. Sunita Verma',
        role: 'NODAL_OFFICER',
      },
      {
        id: 'tl-4',
        status: 'In Progress',
        title: 'Repair Underway',
        description: 'Worker arrived at site, bitumen resurfacing machinery deployed.',
        timestamp: '2026-08-22T14:15:00Z',
        performedBy: 'Vikram Singh',
        role: 'WORKER',
      },
    ],
  },
  {
    id: 'SB-2026-8902',
    title: 'Water Supply Pipeline Leakage near Shahpura Lake Promenade',
    description: 'Fresh water gushing out from broken municipal distribution valve near Shahpura Park gate 2.',
    category: 'Water Supply & Sewage',
    status: 'Submitted',
    priority: 'CRITICAL',
    location: {
      address: 'Shahpura Lake Park Gate 2, Ward 52',
      ward: 'Ward 52 - Shahpura',
      lat: 23.1954,
      lng: 77.4290,
    },
    citizenId: 'user-cit-001',
    citizenName: 'Priya Nambiar',
    citizenPhone: '+91 94254 11223',
    images: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=600&auto=format&fit=crop&q=80'],
    createdAt: '2026-08-23T08:00:00Z',
    updatedAt: '2026-08-23T08:05:00Z',
    estimatedResolutionDays: 1,
    aiAnalysis: {
      autoCategory: 'Water Supply & Sewage',
      predictedPriority: 'CRITICAL',
      confidenceScore: 0.98,
      isDuplicateDetected: true,
      duplicateComplaintId: 'SB-2026-8890',
      duplicateSimilarity: 0.88,
      recommendedWorkerDept: 'Jal Nigam & Municipal Hydraulics',
      imageVerified: true,
      imageVerificationNote: 'AI flagged high severity main line leakage. Nearby duplicate recorded 2h ago.',
    },
    timeline: [
      {
        id: 'tl-10',
        status: 'Submitted',
        title: 'Complaint Registered',
        description: 'High priority water leak logged by citizen.',
        timestamp: '2026-08-23T08:00:00Z',
        performedBy: 'Priya Nambiar',
        role: 'CITIZEN',
      },
    ],
  },
  {
    id: 'SB-2026-8875',
    title: 'Broken Streetlight Pole & Dark Alley in Arera Colony E-3',
    description: 'Streetlight pole #AR-402 knocked down by fallen tree branch, leaving entire residential crossroad in complete darkness at night.',
    category: 'Street Lighting',
    status: 'Completed',
    priority: 'MEDIUM',
    location: {
      address: 'Lane 4, E-3 Arera Colony',
      ward: 'Ward 48 - Arera Colony',
      lat: 23.2125,
      lng: 77.4385,
    },
    citizenId: 'user-cit-001',
    citizenName: 'Rajesh Sharma',
    citizenPhone: '+91 98930 12345',
    images: ['https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=80'],
    createdAt: '2026-08-18T18:20:00Z',
    updatedAt: '2026-08-20T11:30:00Z',
    estimatedResolutionDays: 2,
    assignedWorkerId: 'user-wrk-102',
    assignedWorkerName: 'Ramesh Patel',
    assignedWorkerPhone: '+91 98261 44556',
    assignedDepartment: 'Electrical & Lighting Cell',
    nodalOfficerId: 'user-nod-201',
    nodalOfficerName: 'Er. Sunita Verma',
    resolutionProof: {
      images: ['https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&auto=format&fit=crop&q=80'],
      notes: 'Replaced damaged junction box, installed new 90W LED fixture and branch trimmed.',
      completedAt: '2026-08-20T10:30:00Z',
      verifiedByOfficer: true,
      verifiedAt: '2026-08-20T11:30:00Z',
    },
    aiAnalysis: {
      autoCategory: 'Street Lighting',
      predictedPriority: 'MEDIUM',
      confidenceScore: 0.92,
      isDuplicateDetected: false,
      recommendedWorkerDept: 'Electrical & Lighting Cell',
      imageVerified: true,
      imageVerificationNote: 'AI verified dark streetlight pole location.',
    },
    timeline: [
      {
        id: 'tl-20',
        status: 'Submitted',
        title: 'Complaint Registered',
        description: 'Reported with photos.',
        timestamp: '2026-08-18T18:20:00Z',
        performedBy: 'Rajesh Sharma',
        role: 'CITIZEN',
      },
      {
        id: 'tl-21',
        status: 'Completed',
        title: 'Work Completed & Verified',
        description: 'Electrical team restored lighting and officer verified execution.',
        timestamp: '2026-08-20T11:30:00Z',
        performedBy: 'Er. Sunita Verma',
        role: 'NODAL_OFFICER',
      },
    ],
  },
  {
    id: 'SB-2026-8850',
    title: 'Uncleared Construction Debris near New Market Bus Stop',
    description: 'Large pile of concrete rubble blocks pedestrian footpath near TT Nagar Stadium entry.',
    category: 'Garbage & Sanitation',
    status: 'Escalated',
    priority: 'HIGH',
    isEscalated: true,
    escalationReason: 'Resolution SLA exceeded by 48 hours without worker progress update.',
    location: {
      address: 'TT Nagar Stadium Circle, New Market',
      ward: 'Ward 35 - New Market',
      lat: 23.2389,
      lng: 77.4012,
    },
    citizenId: 'user-cit-99',
    citizenName: 'Amitabh Jain',
    citizenPhone: '+91 99260 33445',
    images: ['https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop&q=80'],
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-22T17:00:00Z',
    nodalOfficerId: 'user-nod-201',
    nodalOfficerName: 'Er. Sunita Verma',
    aiAnalysis: {
      autoCategory: 'Garbage & Sanitation',
      predictedPriority: 'HIGH',
      confidenceScore: 0.91,
      isDuplicateDetected: false,
      recommendedWorkerDept: 'Solid Waste & Heavy Debris Wing',
      imageVerified: true,
    },
    timeline: [
      {
        id: 'tl-30',
        status: 'Submitted',
        title: 'Complaint Registered',
        description: 'Reported by Citizen.',
        timestamp: '2026-08-15T10:00:00Z',
        performedBy: 'Amitabh Jain',
        role: 'CITIZEN',
      },
      {
        id: 'tl-31',
        status: 'Escalated',
        title: 'Escalated to Higher Authority',
        description: 'Auto-escalated due to SLA timeout.',
        timestamp: '2026-08-22T17:00:00Z',
        performedBy: 'System AI Monitor',
        role: 'SYSTEM',
      },
    ],
  },
];

export const INITIAL_WORKER_TASKS = [
  {
    id: 'TSK-1001',
    complaintId: 'SB-2026-8901',
    title: 'Resurface Link Road 1 Potholes near Board Office Square',
    category: 'Roads & Potholes',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    location: {
      address: 'Link Road 1, Near Board Office Square, MP Nagar Zone I',
      ward: 'Ward 43 - MP Nagar Zone I',
      lat: 23.2315,
      lng: 77.4338,
    },
    scheduledDate: '2026-08-23',
    instructions: 'Deploy cold-mix asphalt patch team. Ensure compaction and safety cone layout prior to opening traffic lane.',
    beforeImages: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=600&auto=format&fit=crop&q=80'],
  },
  {
    id: 'TSK-1002',
    complaintId: 'SB-2026-8910',
    title: 'Clear Drainage Clogging near Hamidia Hospital Gate 1',
    category: 'Water Supply & Sewage',
    priority: 'CRITICAL',
    status: 'PENDING',
    location: {
      address: 'Hamidia Hospital Gate 1, Ward 12',
      ward: 'Ward 12 - Hamidia',
      lat: 23.2580,
      lng: 77.4010,
    },
    scheduledDate: '2026-08-23',
    instructions: 'Use suction super-sucker truck to clear storm water drain blockage.',
    beforeImages: ['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?w=600&auto=format&fit=crop&q=80'],
  },
  {
    id: 'TSK-1003',
    complaintId: 'SB-2026-8875',
    title: 'Replace Damaged LED Light Pole in Arera Colony E-3',
    category: 'Street Lighting',
    priority: 'MEDIUM',
    status: 'VERIFIED',
    location: {
      address: 'Lane 4, E-3 Arera Colony',
      ward: 'Ward 48 - Arera Colony',
      lat: 23.2125,
      lng: 77.4385,
    },
    scheduledDate: '2026-08-19',
    instructions: 'Install 90W LED fixture and test connection.',
    beforeImages: ['https://images.unsplash.com/photo-1509114397022-ed747cca3f65?w=600&auto=format&fit=crop&q=80'],
    afterImages: ['https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=600&auto=format&fit=crop&q=80'],
    workerNotes: 'Task completed successfully. Tested LED glow at dusk.',
    completedAt: '2026-08-20T10:30:00Z',
  },
];

export const INITIAL_NGO_AREAS = [
  {
    id: 'ngo-a1',
    wardNumber: 'Ward 48',
    wardName: 'Arera Colony (E-1 to E-5)',
    activeComplaintsCount: 4,
    resolvedComplaintsCount: 42,
    volunteersCount: 28,
    assignedNGO: 'Green Bhopal Foundation',
    coverageStatus: 'ACTIVE',
  },
  {
    id: 'ngo-a2',
    wardNumber: 'Ward 52',
    wardName: 'Shahpura & Lake Promenade',
    activeComplaintsCount: 7,
    resolvedComplaintsCount: 38,
    volunteersCount: 34,
    assignedNGO: 'Green Bhopal Foundation',
    coverageStatus: 'HIGH_PRIORITY',
  },
  {
    id: 'ngo-a3',
    wardNumber: 'Ward 43',
    wardName: 'MP Nagar Commercial Hub',
    activeComplaintsCount: 9,
    resolvedComplaintsCount: 65,
    volunteersCount: 19,
    assignedNGO: 'Green Bhopal Foundation',
    coverageStatus: 'SATISFACTORY',
  },
];

export const INITIAL_VOLUNTEERS = [
  {
    id: 'vol-1',
    name: 'Aarav Mehta',
    email: 'aarav.m@example.com',
    phone: '+91 98270 11223',
    ward: 'Ward 48 - Arera Colony',
    status: 'ACTIVE',
    joinedDate: '2026-01-15',
    assignedActivitiesCount: 12,
    pointsEarned: 340,
  },
  {
    id: 'vol-2',
    name: 'Divya Raghunath',
    email: 'divya.r@example.com',
    phone: '+91 94065 44332',
    ward: 'Ward 52 - Shahpura',
    status: 'ACTIVE',
    joinedDate: '2026-03-02',
    assignedActivitiesCount: 9,
    pointsEarned: 280,
  },
  {
    id: 'vol-3',
    name: 'Siddharth Saxena',
    email: 'sid.saxena@example.com',
    phone: '+91 99931 77889',
    ward: 'Ward 43 - MP Nagar',
    status: 'INACTIVE',
    joinedDate: '2025-11-10',
    assignedActivitiesCount: 5,
    pointsEarned: 110,
  },
];

export const INITIAL_EVENTS = [
  {
    id: 'evt-101',
    title: 'Upper Lake Front Cleanliness & Plastic Abatement Drive',
    type: 'Cleanliness Drive',
    location: 'VIP Road Promenade & Boat Club Shoreline',
    ward: 'Ward 24 - VIP Road',
    date: '2026-08-28',
    time: '07:00 AM - 10:00 AM',
    volunteersEnrolled: 45,
    targetVolunteers: 60,
    status: 'UPCOMING',
    organizer: 'Green Bhopal Foundation',
  },
  {
    id: 'evt-102',
    title: 'Shahpura Lake Bio-Shield Sapling Plantation Drive',
    type: 'Tree Plantation',
    location: 'Shahpura Lake Sector 3 Park',
    ward: 'Ward 52 - Shahpura',
    date: '2026-09-02',
    time: '08:00 AM - 11:30 AM',
    volunteersEnrolled: 30,
    targetVolunteers: 50,
    status: 'UPCOMING',
    organizer: 'Green Bhopal Foundation',
  },
];

export const INITIAL_REWARDS = [
  {
    id: 'rew-1',
    title: 'Green Citizen Pioneer Badge',
    description: 'Awarded for registering at least 3 verified civic complaints.',
    category: 'Badge',
    pointsRequired: 100,
    icon: 'ShieldCheck',
    unlocked: true,
    unlockedAt: '2026-08-10',
  },
  {
    id: 'rew-2',
    title: 'Bhopal Eco-Champion Digital Certificate',
    description: 'Official BMC recognition for active community civic participation.',
    category: 'Certificate',
    pointsRequired: 300,
    icon: 'Award',
    unlocked: true,
    unlockedAt: '2026-08-20',
  },
  {
    id: 'rew-3',
    title: 'City Transport Metro Pass Discount Voucher',
    description: '20% rebate on Bhopal Metro Monthly Commuter Pass.',
    category: 'Voucher',
    pointsRequired: 500,
    icon: 'Ticket',
    unlocked: false,
  },
  {
    id: 'rew-4',
    title: 'Mayor Civic Honor Roll Certificate',
    description: 'Prestigious award presented quarterly for top-ranking ward contributors.',
    category: 'Recognition',
    pointsRequired: 1000,
    icon: 'Crown',
    unlocked: false,
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Complaint Status Updated',
    message: 'Your complaint SB-2026-8901 (Link Road 1 Potholes) is now IN PROGRESS.',
    type: 'complaint',
    timestamp: '10 mins ago',
    read: false,
    targetId: 'SB-2026-8901',
  },
  {
    id: 'notif-2',
    title: 'Points & Reward Unlocked!',
    message: 'You earned 50 Smart Bhopal points for verified report SB-2026-8875.',
    type: 'reward',
    timestamp: '2 hours ago',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'New Task Assignment',
    message: 'Nodal Officer assigned Task TSK-1002 (Hamidia Drain) to your queue.',
    type: 'worker',
    timestamp: 'Yesterday',
    read: true,
    targetId: 'TSK-1002',
  },
];

export const ANALYTICS_DATA = {
  totalComplaints: 1248,
  activeComplaints: 142,
  pendingComplaints: 86,
  resolvedComplaints: 1045,
  escalatedComplaints: 15,
  avgResolutionTimeHours: 28.4,
  citizenSatisfactionRate: 94.2,
  monthlyTrends: [
    { month: 'Mar', submitted: 180, resolved: 172 },
    { month: 'Apr', submitted: 210, resolved: 198 },
    { month: 'May', submitted: 245, resolved: 230 },
    { month: 'Jun', submitted: 310, resolved: 285 },
    { month: 'Jul', submitted: 390, resolved: 360 },
    { month: 'Aug', submitted: 420, resolved: 395 },
  ],
  categoryBreakdown: [
    { name: 'Roads & Potholes', value: 38 },
    { name: 'Water & Sewage', value: 24 },
    { name: 'Garbage & Sanitation', value: 18 },
    { name: 'Street Lighting', value: 12 },
    { name: 'Parks & Amenities', value: 8 },
  ],
  wardPerformance: [
    { ward: 'Ward 48 (Arera)', total: 140, resolved: 132, pending: 8 },
    { ward: 'Ward 43 (MP Nagar)', total: 210, resolved: 190, pending: 20 },
    { ward: 'Ward 52 (Shahpura)', total: 165, resolved: 150, pending: 15 },
    { ward: 'Ward 12 (Hamidia)', total: 195, resolved: 170, pending: 25 },
    { ward: 'Ward 35 (New Market)', total: 180, resolved: 160, pending: 20 },
  ],
  workerPerformance: [
    { name: 'Vikram Singh', completed: 48, avgTimeHours: 19.2, rating: 4.9 },
    { name: 'Ramesh Patel', completed: 42, avgTimeHours: 22.5, rating: 4.8 },
    { name: 'Sanjay Kumar', completed: 39, avgTimeHours: 24.1, rating: 4.7 },
    { name: 'Deepak Chouhan', completed: 35, avgTimeHours: 26.0, rating: 4.6 },
  ],
};

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'log-1',
    timestamp: '2026-08-23 11:45:12',
    user: 'Er. Sunita Verma',
    role: 'NODAL_OFFICER',
    action: 'ASSIGN_WORKER',
    details: 'Assigned complaint SB-2026-8901 to Vikram Singh (Road Wing)',
    ipAddress: '10.240.12.89',
  },
  {
    id: 'log-2',
    timestamp: '2026-08-23 10:20:05',
    user: 'Rajesh Sharma',
    role: 'CITIZEN',
    action: 'CREATE_COMPLAINT',
    details: 'Submitted geotagged complaint SB-2026-8902 for Shahpura ward',
    ipAddress: '157.34.88.12',
  },
  {
    id: 'log-3',
    timestamp: '2026-08-22 17:00:00',
    user: 'System AI Engine',
    role: 'SUPER_ADMIN',
    action: 'AUTO_ESCALATE',
    details: 'Escalated SB-2026-8850 to Higher Authority due to SLA timeout',
    ipAddress: '127.0.0.1',
  },
];
